theme: jekyll-theme-minimal
title: Lioba Enk
email: "enk.lioba@gmail.com"
institution_profile: "https://www.cbs.mpg.de/person/enk/1770355"
google_scholar: "https://scholar.google.com/citations?user=Mt8xFO8AAAAJ&hl=en&oi=ao"
